# name: Movies CI/CD
# version: 1.0.0
# languages:
#     - Python
#     - Javascript

name: Movies CI/CD

# Triggers for the workflow
on:
    # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    
    # Automatic trigger on push events to the main branch
    push:
      branches:
        - main
        
    # Automatic trigger on pull request events targeting the main branch
    pull_request:
      branches:
        - main
      paths:
        - 'backend/**'

defaults:
    run:
        working-directory: ./backend
jobs:
  # Continuous Integration job
    ci_for_backend:
      runs-on: ubuntu-latest
      
      environment:
            name: Deployment
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
        
          - name: Install dependencies
            run: |
              pip install pipenv --user

              pipenv install


          - name: Linting
            id: lint
            run: pipenv run lint

          - name: Tests
            id: tests
            run: pipenv run test


        
# Continuous Deployment job
    cd_for_backend:
      needs: [ci_for_backend]
      runs-on: ubuntu-latest
      environment:
        name: Deployment
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
    
        - name: Install dependencies
          run: |
            pip install pipenv --user

            pipenv install

            # pip install flake8
            # pip install pytest

        - name: Linting
          id: lint
          run: pipenv run lint

        - name: Tests
          id: tests
          run: pipenv run test

 
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
            aws-region: us-east-1
        - name:  Login to Amazon ECR
          id: ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build the docker image
          env: 
            ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
            ECR_REPOSITORY: backend
          run: |
              docker build -t sidahmedfaisal/backend:${GITHUB_SHA::7} .
              docker push sidahmedfaisal/backend:${GITHUB_SHA::7}
            
