# name: Movies CI/CD
# version: 1.0.0
# languages:
#     - Python
#     - Javascript

name: Movies CI/CD

# Triggers for the workflow
on:
    # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    
    # Automatic trigger on push events to the main branch
    push:
      branches:
        - main
        
    # Automatic trigger on pull request events targeting the main branch
    pull_request:
      branches:
        - main
      paths:
        - 'frontend/**'

defaults:
    run:
        working-directory: ./frontend
jobs:
  # Continuous Integration job
    ci:
      runs-on: ubuntu-latest
      
      environment:
            name: Deployment
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 18.14
        
          - name: Install dependencies
            run: npm install

          - name: Linting
            id: lint
            run: npm run lint --fix

          - name: Tests
            id: tests
            run: CI=true npm test --passWithNoTests

          - name: Build
            if: steps.lint.outcome == 'success' && steps.tests.outcome == 'success'
            run: npm run build

  # Continuous Deployment job
    cd:
      runs-on: ubuntu-latest
      
      environment:
            name: Deployment

      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 18.14
      

